apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-hello
spec:
  selector:
    matchLabels:
      app: go-hello
  replicas: 2 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: go-hello
    spec:
      containers:
        - name: go-hello
          image: robjkc/go-hello:1.0.0
          ports:
            - containerPort: 8082