apiVersion: v1
kind: Pod
metadata:
  name: go-hello
  labels:
    app.kubernetes.io/name: go-hello
spec:
  containers:
    - name: go-hello
      image: robjkc/go-hello:1.0.0
      ports:
        - containerPort: 8082
          name: http-web-svc

---

apiVersion: v1
kind: Service
metadata:
  name: go-hello-service
spec:
  selector:
    app.kubernetes.io/name: go-hello
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: http-web-svc