apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-hello
  labels:
    app: go-hello
spec:
  replicas: 1
  selector:
    matchLabels:
      app: go-hello
  template:
    metadata:
      labels:
        app: go-hello
    spec:
      hostNetwork: true
      containers:
        - name: go-hello
          image: go-hello-image
          ports:
            - containerPort: 8082

---
apiVersion: v1
kind: Service
metadata:
  name: go-hello-service
spec:
  selector:
    app: go-hello
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8082